# Start the app using docker-compose pull && docker-compose up to make sure you have the latest image
version: "2.4"
services:
  postgres:
    image: postgres
    build: .
     # Make Postgres log to a file.
     # More on logging with Postgres: https://www.postgresql.org/docs/current/static/runtime-config-logging.html
    command: postgres -c logging_collector=on -c log_destination=stderr -c log_directory=/logs
    environment:
       # Provide the password via an environment variable. If the variable is unset or empty, use a default password
        - POSTGRES_PASSWORD=mysecretpassword

     # If on a non-Linux OS, make sure you share the drive used here. Go to Docker's settings -> Shared Drives
    volumes:
       # Persist the data between container invocations
        - ./logs:/logs
        - ./customPostgresql.conf:/etc/postgresql.conf      
    ports:
        - 5432:5432   

